version: 'v1.0'

services:
  fastapi:
    build: fastapi/
    ports: 
      - 8500:8500
    networks:
      - deploy_network
    container_name: backend

  streamlit:
    build: streamlit/
    depends_on:
      - fastapi
    ports: 
        - 8501:8501
    networks:
      - deploy_network
    container_name: frontend

networks:
  deploy_network:
    driver: bridge